name: CI/CD Development
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  web-deploy:
    name: auto deploy
    runs-on: ubuntu-latest

    steps:
      - name: get latest code
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./
          server-dir: public_html/konsera.kaitodecode.com/
          exclude: |
            .git*
            node_modules*
            vendor*
            storage/imports*
